github-actions

diff --git a/.github/workflows/non-prod-pipeline.yaml b/.github/workflows/non-prod-pipeline.yaml
--- a/.github/workflows/non-prod-pipeline.yaml
+++ b/.github/workflows/non-prod-pipeline.yaml
@@ -19,6 +19,41 @@ jobs:
         APP_VERSION=$(echo "${{ inputs.version }}" | cut -c1-7)
         echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
         echo "Using commit: $APP_VERSION"
+
+    - name: Commit ID
+      id: commit
+      run: |
+        APP_VERSION=$(echo "${{ inputs.version }}" | cut -c1-7)
+        echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
+        echo "Using commit: $APP_VERSION"
+
+
+    - name: Check Commit Status
+      env:
+        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      run: |
+
+        COMMIT_SHA=${{ inputs.version }}
+
+        echo "Checking commit:"
+        echo $COMMIT_SHA
+
+
+        STATUS=$(gh api \
+        repos/${{ github.repository }}/commits/$COMMIT_SHA/status \
+        --jq '.state')
+
+
+        echo "Commit status: $STATUS"
+
+
+        if [ "$STATUS" != "success" ]; then
+          echo "❌ Commit checks failed"
+          exit 1
+        fi
+
+
+        echo "✅ Commit checks passed"
     
         
         
